---
- name: agile defense website
  hosts: all
  remote_user: ansible
  become: true
  become_method: sudo
  become_user: root

  tasks:
  - name: set index.html
    copy: src=/ansible_templates/agiledefense.html dest=/var/www/html/index.html owner=root group=root mode=0444
  - name: set image
    copy: src=/ansible_templates/agiledefense.png dest=/var/www/html/agiledefense.png owner=root group=root mode=0444
  - name: restart httpd
    service: name=httpd state=restarted
