---
- name: set COS OSS Meet hello world
  hosts: all
  remote_user: ansible
  become: true
  become_method: sudo
  become_user: root

  tasks:
  - name: set index.html
    copy: src=/ansible_templates/cosossmeethello.html dest=/var/www/html/index.html owner=root group=root mode=0444
  - name: restart httpd
    service: name=httpd state=restarted
