---
- name: egs app deploy
  hosts: all
  become: true
  become_method: sudo
  become_user: root

  tasks:
  - name: set index.html
    copy: src=ansiblecontent/egs.html dest=/var/www/html/index.html owner=root group=root mode=0444
  - name: set image
    copy: src=ansiblecontent/egs.jpg dest=/var/www/html/egs.jpg owner=root group=root mode=0444
  - name: restart httpd
    service: name=httpd state=restarted
