---
- name: configure firewalld for https only
  hosts: all
  remote_user: ansible
  become: true
  become_method: sudo
  become_user: root

  tasks:
  - name: enable https
    firewalld: service=https permanent=true state=enabled immediate=yes
  - name: disable http
    firewalld: service=http permanent=true state=disabled immediate=yes
