---
- name: set Sweet App index.html
  hosts: all
  remote_user: ansible
  become: true
  become_method: sudo
  become_user: root

  tasks:
  - name: set index.html
    copy: src=/ansible_templates/sweetapp.html dest=/var/www/html/index.html owner=root group=root mode=0444
  - name: set dosug.jpeg
    copy: src=/ansible_templates/dosug.jpeg dest=/var/www/html/dosug.jpeg owner=root group=root mode=0444
  - name: restart httpd
    service: name=httpd state=restarted
