---
- name: set Wright Pat index.html
  hosts: all
  remote_user: ansible
  become: true
  become_method: sudo
  become_user: root

  tasks:
  - name: set index.html
    copy: src=/ansible_templates/wpafb.html dest=/var/www/html/index.html owner=root group=root mode=0444
  - name: set image
    copy: src=/ansible_templates/wpafb.png dest=/var/www/html/wpafb.png owner=root group=root mode=0444
  - name: restart httpd
    service: name=httpd state=restarted
